# Generated by Django 4.1.4 on 2022-12-26 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaytestEmailSignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Emails of users that want to participate in playtest', max_length=254, null=True)),
            ],
        ),
    ]
