version: "3.7"

services:

    db:
      image: postgres:14
      restart: always
      volumes:
        - postgress_db:/var/lib/postgresql/data

      environment:
        - POSTGRES_NAME=${DB_NAME}
        - POSTGRES_USER=${DB_USERNAME}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: "10s"
        timeout: "5s"
        retries: 5
        start_period: "10s"

    dw_studio_production:
      image: ghcr.io/p0lygun/deep_worlds_studio/main:latest
      restart: always
      command: bash -c "python manage.py migrate --noinput && python manage.py ensure_superuser --username '${SU_USERNAME}'  --email gala@stilllearning.tech --password '${SU_PASSWD}' && python manage.py runserver 0.0.0.0:${PRODUCTION_PORT} --settings=website.settings.production"
      ports:
        - "${PRODUCTION_PORT}:${PRODUCTION_PORT}"
      environment:
        - PRODUCTION_KEY=${PRODUCTION_KEY}
        - DB_NAME=${DB_NAME}
        - DB_USERNAME=${DB_USERNAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_PORT=${DB_PORT}
        - POSTGRES_HOST=db # takes precedent over .env file

        - EMAIL_HOST=${EMAIL_HOST}  # the serve which will acctually send the email
        - EMAIL_PORT=${EMAIL_PORT}
        - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}  # this will be the email that will show up in From
        - EMAIL_PASSWORD=${EMAIL_PASSWORD}
        - DEFAULT_TO_EMAIL=${DEFAULT_TO_EMAIL}
      depends_on:
        - db
      healthcheck:
        test: curl -fk http://0.0.0.0:${PRODUCTION_PORT}/ || exit 1
        interval: "60s"
        timeout: "3s"
        retries: 3
        start_period: "5s"
